/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "home": [],
    "companies": [],
    "companies.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "companies.submitClaim": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "companies.reviews.store": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "companies.follow": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "companies.unfollow": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "companies.submit": [],
    "jobs": [],
    "jobs.show": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "jobs.apply": [
        {
            "name": "slug",
            "required": true
        }
    ],
    "jobs.apply.store": [
        {
            "name": "job",
            "required": true,
            "binding": "slug"
        }
    ],
    "search": [],
    "about": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "logout": [],
    "admin.dashboard": [],
    "admin.submissions": [],
    "admin.submission": [
        {
            "name": "submission",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.submission.update": [
        {
            "name": "submission",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.claims": [],
    "admin.claim": [
        {
            "name": "claim",
            "required": true,
            "binding": "id"
        }
    ],
    "admin.claim.update": [
        {
            "name": "claim",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "dashboard.view": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.edit": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.applications": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.application.update": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "application",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard.jobs": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.jobs.create": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.jobs.store": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.jobs.edit": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "job",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.jobs.update": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "job",
            "required": true,
            "binding": "slug"
        }
    ],
    "dashboard.jobs.destroy": [
        {
            "name": "company",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "job",
            "required": true,
            "binding": "slug"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
