name: Lint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  pint:
    name: Fomatting PHP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
      - name: Install Pint
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Pint (Lint)
        run: ./vendor/bin/pint --test
  eslint:
    name: Lint TS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint (Lint)
        run: pnpm lint:check
  prettier:
    name: Format TS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint (Lint)
        run: pnpm format:check
  typescript:
    name: Check TS types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tsc (TypeScript Compiler)
        run: pnpm types
