name: TypeScript

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  typescript:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tsc (TypeScript Compiler)
        run: pnpm types
